name: Scrape folk metal bands

on:
  schedule:
    - cron: 0 1 1 * *

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - run: |
          python3 -m pip install -r src/requirements.txt
          python3 src/scrape_folk_metal_bands.py